### ISSUE TITLE
backup giving error

### ISSUE THREAD

**Issue by varmab** [bandraszyk/contentful-emails#2]
gulp contentful-backup

This command giving an error. Any ideas?

fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/Users/varmabhupatiraju/projects/contentful-emails/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/varmabhupatiraju/projects/contentful-emails/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/varmabhupatiraju/projects/contentful-emails/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)

**Comment by varmab** [comment]
I was able to fix my error. It is to do with Node and Gulp versions. I followed this https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node to fix my issue
